[package]
name = "pong"
version = "0.1.0"
authors = ["André Claudino <andre.claudino@b2wdigital.com>"]
edition = "2018"

[dependencies]
tetra = "0.5"

[lib]
name = "pong_library"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "pong"
path = "src/main.rs"